import { createClient } from '@supabase/supabase-js'

export const supabaseUrl = 'https://cpdaldaajjvmgjkbujii.supabase.co'
export const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZGFsZGFhamp2bWdqa2J1amlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUzNjkzMDgsImV4cCI6MjAxMDk0NTMwOH0.SbCFUZksrZFs84VR59KvQZJMJQVBaoZDJzuMdfK6Y7Q'

// export const supabase = createClient('https://pzylczakicuqhqlpwnvs.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eWxjemFraWN1cWhxbHB3bnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTM5MTk3ODksImV4cCI6MjAwOTQ5NTc4OX0.tjMfim5zcfB_NZ0oqeo9xQq2CNqGy7ch11R0wbFQTHM')

export const supabase = createClient(supabaseUrl, supabaseKey)